# Generated by Django 4.2.3 on 2023-07-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField()),
                ('total_units', models.IntegerField()),
                ('performance_hours_offset', models.IntegerField()),
            ],
        ),
    ]
